# Configuração do analisador estático. Corre com `flutter analyze`.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - prefer_single_quotes
    - prefer_final_locals
    - unnecessary_late
    - use_super_parameters
    - directives_ordering
    - require_trailing_commas
    - sort_child_properties_last
    - unawaited_futures
