/// Texto de ajuda por página. Linguagem simples, sem jargão — o público-alvo
/// tem dificuldade com tecnologia.
library;

enum HelpTopic {
  dashboard,
  ingredientes,
  receitas,
  receitaDetalhe,
  fichas,
  fichaDetalhe,
  produzir,
  agendar,
  agenda,
  planoDetalhe,
  compras,
  comprasRelatorio,
  inventario,
  faturas,
  faturaRevisao,
  vendas,
  analiseVendas,
  encomendas,
  contagem,
  haccp,
  colaboradores,
  custosFixos,
  equipamentos,
  numerosMagicos,
  painelFinanceiro,
  dre,
  contabilidade,
  embalagens,
  variacoesPreco,
  aprovacoes,
  avisos,
  lotes,
  rentabilidade,
  pessoasPonto,
  saudeDados,
  pessoasEscala,
  pessoasFerias,
  pessoasNotas,
  pessoasFormacoes,
  previsaoAssar,
  tabelaRevendedores,
  consumiveis,
  produtos,
  configuracoes,
  navegacao,
  equipa,
}

typedef HelpEntry = ({String titulo, List<String> paragrafos});

const Map<HelpTopic, HelpEntry> helpContent = {
  HelpTopic.dashboard: (
    titulo: 'Início',
    paragrafos: [
      'O Início mostra só o que precisa de ti hoje, e deixa resolver quase tudo ali mesmo, sem abrir outras páginas.',
      'Em cima: os teus 3 atalhos (Produzir agora, Quantos assar, Contagem…). O botão com os cursores escolhe quais — fica guardado só neste aparelho, e cada pessoa tem os seus.',
      'O que está no forno aparece logo a seguir (e avisa quando é para tirar).',
      '"Precisa de ti" junta o que pede ação, com o ponto de cor: vermelho = urgente (backup com problema, HACCP, validade ou formação caducada, encomenda daqui a pouco, pagamento nos próximos 2 dias); laranja = para fazer hoje.',
      'Quando há um botão na linha, resolve ali: "Aprovar" férias (com "Desfazer" durante uns segundos) ou contas novas, "Renovar" um certificado, "Saída às 16:30" para a saída esquecida (com a hora do fim do turno), "Rever" uma fatura. Se um grupo tem vários itens (várias férias, vários certificados), toca na linha para os abrir e usar o botão de cada um; "Abrir página" leva à página completa.',
      'Sem botão, tocar na linha abre a página certa (Inventário, Compras, HACCP, Encomendas…).',
      '"Para saber" guarda o que não pede nada agora (preços que subiram, produções agendadas, pagamentos daqui a mais de 2 dias). Está fechado para não ocupar espaço.',
      'Se não houver nada, vês "Tudo em dia".',
      'O botão "Mais" (último do rodapé) e a lupa abrem todas as páginas, agrupadas por tarefa, com uma pesquisa em cima: escreve "férias", "preços", o nome de uma ficha, de uma receita ou de um ingrediente e toca no resultado (Enter abre o primeiro). Mantém o dedo num ícone para mudar a sua cor. As páginas do rodapé e o que cada pessoa pode ver ou editar definem-se em Configurações → Navegação e permissões.',
      'O botão "?" existe em todas as páginas e abre esta explicação; dentro dele também estão as "Notas desta página" (para deixares um aviso à equipa, ex. "falta o preço deste ingrediente") e "Sugestão ou reportar erro" (vai direto para o desenvolvimento).',
    ],
  ),
  HelpTopic.ingredientes: (
    titulo: 'Ingredientes',
    paragrafos: [
      'Lista de tudo o que compra: farinha, manteiga, chocolate, etc.',
      'Cada ingrediente tem o preço, o peso da embalagem e o fornecedor.',
      'Use "+" para adicionar um ingrediente novo. Toque num ingrediente para editar.',
      'Pode importar muitos ingredientes de uma vez a partir de um ficheiro .csv.',
      'Ao criar um ingrediente pode já preencher a informação nutricional e os alergénios (opcional): à mão, escolhendo da tabela INSA, ou com a foto do rótulo (a IA lê e preenche — confira sempre). Deslize um ingrediente para a esquerda para o mover para a lixeira.',
      'O ícone de nutrição em cada linha abre "Nutrição e alergénios": preenche à mão, escolhe da tabela INSA, ou envia uma foto do rótulo para a IA preencher. Depois a informação nutricional das receitas e fichas é calculada sozinha.',
      'Esse ícone diz logo o estado da nutrição (legenda em cima da lista): prato aberto/cinzento = sem nutrição; ⚖ (por rever) = a INSA automática ficou em dúvida; livro = valores da tabela INSA; lápis = preenchido à mão; máquina fotográfica = à mão com a foto da tabela nutricional anexada. Na folha de nutrição podes "Anexar foto (sem IA)" a qualquer momento como prova/referência.',
      'Nos produtos de fabrico próprio, esse ícone abre a lista de ingredientes/subprodutos da receita — não se preenche à mão. Vais tocando em cada um até estar tudo com nutrição: os ingredientes comprados por INSA/foto/manual; os subprodutos Gookie abrem os seus próprios ingredientes, em cascata. O total do produto é calculado no fim.',
      'O menu (⋮) no topo junta três ações: "Juntar marcas/fornecedores repetidos" (só proprietário/administrador — corrige nomes duplicados do mesmo fornecedor, ex. "Makro" e "Makro Cash & Carry"), "Preencher nutrição pela tabela INSA" (percorre os ingredientes SEM nutrição e, quando encontra um alimento claramente igual, preenche os valores e os alergénios — os que ficam em dúvida ficam "por rever", para escolheres da lista) e "Importar CSV".',
      'Ao escrever a marca ou o fornecedor de um ingrediente, a app sugere os nomes já usados na empresa (não é preciso escrever sempre igual) e põe maiúscula na primeira letra sozinha.',
      'O botão de ordenar (seta, ao lado do "?") organiza a lista por Nome, Preço ou Fornecedor — toca outra vez no mesmo critério para inverter a ordem.',
      'Quando muda o preço de um ingrediente, o custo das receitas e das fichas é recalculado sozinho.',
    ],
  ),
  HelpTopic.receitas: (
    titulo: 'Receitas',
    paragrafos: [
      'As suas massas, recheios e coberturas.',
      'Cada receita é feita de ingredientes (e pode usar outras receitas lá dentro).',
      'Use "+" para criar uma receita. Toque numa receita para ver os detalhes e o custo.',
      'O botão + abre duas opções: "Nova receita" (à mão) ou "Importar receitas": cola o texto copiado da folha de cálculo (ou escolhe um CSV) com uma linha por ingrediente — nome da receita, categoria, ingrediente, quantidade em gramas. Os ingredientes sem correspondência ficam pendentes na receita, para ligares depois. Receitas com nome que já existe são ignoradas.',
      'Ao criar uma receita pode já escrever o procedimento e anexar imagens (opcional).',
      'Os chips por baixo da pesquisa filtram por categoria (só mostram as que as tuas receitas realmente usam); as categorias são geríveis em Configurações → Categorias de receitas.',
      'O botão de ordenar (seta) organiza por Nome, Categoria ou Custo — toca outra vez no mesmo critério para inverter a ordem.',
      'Deslize uma receita para a esquerda para a mover para a lixeira. O ícone do caixote do lixo mostra as receitas apagadas, que pode recuperar.',
    ],
  ),
  HelpTopic.receitaDetalhe: (
    titulo: 'Detalhe da receita',
    paragrafos: [
      'Aqui vê as linhas da receita (ingredientes e quantidades) e o custo total.',
      'Botão "Item": adiciona um ingrediente ou uma sub-receita.',
      'Toque numa linha para mudar a quantidade. Deslize para a esquerda para remover.',
      'Ícone do livro: ver e editar o passo-a-passo ("Editar") e as fotos (toca numa foto para ver, substituir ou remover).',
      'Ícone da agenda: enviar esta receita para produzir (vai para o carrinho da agenda).',
      'Ícone do prato: informação nutricional calculada (por 100 g), alergénios agregados, e a % de perda de peso na cozedura (concentra os valores por 100 g de produto).',
    ],
  ),
  HelpTopic.fichas: (
    titulo: 'Fichas técnicas',
    paragrafos: [
      'Uma ficha técnica é o produto final que vende — por exemplo "Cookie Boston".',
      'Junta uma massa, um recheio e/ou uma cobertura, e diz o peso de cada parte.',
      'Serve para saber o custo e o preço de venda sugerido.',
      'Na lista, cada ficha mostra os dois preços: "sugerido" (calculado a partir do custo e dos Percentuais de custo) e "venda" (o preço real que praticas). Toca no preço de venda para o editar sem precisar de abrir a ficha.',
      'O botão de ordenar (seta) organiza por Nome, Custo ou Preço de venda; os chips de categoria (quando há mais do que uma) filtram a lista.',
    ],
  ),
  HelpTopic.fichaDetalhe: (
    titulo: 'Detalhe da ficha técnica',
    paragrafos: [
      'Cada linha é uma parte do produto (massa, recheio, cobertura) com o peso.',
      'Em baixo vê o custo e o preço sugerido, calculado com os percentuais de Configurações.',
      'Ligue a ficha a um "Formato de cookie" para saber quantas unidades saem de cada produção.',
      'CMV esperado: a parte do preço (sem IVA) que reservas para a matéria-prima e embalagem — tu defines em Configurações → Percentuais de custo (ex. 30 %). O que sobra, depois do CMV e dos custos, é a margem de lucro (flexível). CMV real: quanto o custo é do preço de venda que praticas, sem IVA (custo ÷ preço sem IVA). Se o real for maior que o esperado, aparece a vermelho — o preço está baixo para o custo. O "Preço de venda" da ficha é o preço ao público, com IVA. Todas as contas (CMV real, margem, quebra) fazem-se sobre o preço sem IVA: o IVA é cobrado em cima do preço limpo e soma-se por último. A taxa define-se em Configurações → Percentuais de custo → IVA das vendas.',
      'Em "Quebra do preço (sem IVA)" vê cada rubrica (matéria-prima, salário, aluguel, margem…) com valor e % no preço esperado e no real; no real a margem de lucro é o que sobra. No fim aparecem o preço sem IVA, o IVA e o preço final com IVA.',
      '"Preços por canal": a loja física, as plataformas de entrega e os revendedores/terceiros, cada um com as suas taxas em cascata. "Novo canal" cria um (nome + taxas); cada taxa tem um nome, uma % do preço desse nível e/ou um € fixo por venda, pela ordem em que tiram a sua parte do que o cliente paga (a primeira é a de fora, ex.: plataforma; a última a mais perto de nós, ex.: revendedor). Podes ter quantos canais quiseres, cada um com taxas diferentes. Para cada canal vês o preço a cobrar para manteres o lucro da loja — preço limpo + taxas + IVA no fim —, o que cada taxa leva em €, o que chega a nós, o lucro por unidade e uma barra com para onde vai o preço (taxas, custo, estrutura, lucro). Em baixo, "E se vendo ao preço da loja?" mostra o lucro se não subires o preço e a taxa máxima que aguentas antes de dar prejuízo. Os canais são da empresa: criados uma vez, aparecem em todas as fichas.',
      '"Quanto posso cobrar? (revenda)" (dentro da Quebra do preço): mostra o preço de equilíbrio sem IVA (abaixo dele dás prejuízo) e o desconto máximo. Escreve ou toca num desconto (5, 10, 15, 20 %) e vê o preço sem IVA, o IVA, o que cobrar ao revendedor (preço + IVA), o lucro por unidade e a margem. O desconto aplica-se ao preço sem IVA.',
      'Ícone do prato: a Informação do produto — declaração nutricional (por 100 g e por unidade), ingredientes, alergénios e a impressão da etiqueta.',
      '"Tempo de assadura" e "Temperatura do forno" (em Editar ficha): os minutos e os °C do forno do produto — aparecem juntos ("Assar a 170 °C durante 11 min") na ficha, na montagem, na agenda e nos botões de assar da Contagem; se puseres no forno sabores com temperaturas diferentes, a Contagem avisa. Tempo de assadura: os minutos de forno do produto. Aparece aqui como "Assar X min", na Mise en place / Produzir e na Agenda, e é o tempo do cronómetro do forno.',
      'O custo aparece separado: "Matéria-prima" (ingredientes, massa, recheios, coberturas) e "Embalagem" (o bloco Embalagem). O custo do produto na loja é a soma dos dois.',
      '"Embalagem para plataformas" é um bloco à parte para o que só usas nas vendas por Uber Eats, Glovo, etc. (saco de entrega, selo, caixa extra). Não entra no custo da loja nem no preço sugerido: aparece em "Nas plataformas" (custo da loja + esta embalagem), para saberes quanto o produto custa quando vai para uma plataforma.',
    ],
  ),
  HelpTopic.produzir: (
    titulo: 'Produzir',
    paragrafos: [
      'A Produção junta duas secções: "Produzir" (fazer ou planear já) e "Agenda" (as produções planeadas, por dia).',
      'Escolhe o que produzir: um PRODUTO FINAL das fichas técnicas (Boston, Provença…) ou uma receita (massa, recheio, base).',
      'Produto final: indica as unidades. Aparece o mise en place — "Produzir primeiro" (a massa, os recheios e as coberturas, com as gramas de cada um; "Abrir" mostra a receita, o procedimento e as imagens) e os ingredientes a pesar, com o que tens em stock (a vermelho quando falta). O tempo de forno aparece em "Assar X min".',
      'Receita: indica os kg (e, se for produto final, o formato) para ver quanto precisas de cada ingrediente. As quantidades são escaladas pela percentagem de cada ingrediente para dar exatamente os kg pedidos. "Custo por receita" mostra o custo de cada sub-receita. "Procedimento e imagens" mostra o passo-a-passo.',
      'Vai marcando as caixas à medida que preparas. "Produção feita" regista a produção na Agenda como concluída, dá baixa no stock e pergunta se queres juntar à lista de compras o que faltou.',
      'Botão "Agendar": para fazer noutro dia. Num produto final só escolhes a prioridade e a hora limite; numa receita escolhes se é "Produto final" (com formato/ficha técnica → conta unidades) ou "Intermédio" (recheio, massa, base → entra em stock a granel em gramas).',
      'Quando tiveres as receitas todas no carrinho, toca na barra em baixo para "Rever e agendar".',
    ],
  ),
  HelpTopic.agendar: (
    titulo: 'Rever e agendar',
    paragrafos: [
      'Confirme as receitas que vai produzir.',
      'Escolha o dia e, se quiser, um título. Se deixar vazio, fica "Produção de hoje" (ou "Produção DD/MM/AAAA") com os nomes das receitas — e pode sempre editar depois.',
      'Toque em "Criar produção" para a guardar na Agenda.',
    ],
  ),
  HelpTopic.agenda: (
    titulo: 'Agenda de produção',
    paragrafos: [
      'As suas produções, agrupadas por dia.',
      'Cada cartão mostra quantas receitas tem, a hora mais cedo e o custo.',
      'Toque para abrir. Use "Nova produção" para começar uma do zero.',
    ],
  ),
  HelpTopic.planoDetalhe: (
    titulo: 'Detalhe da produção',
    paragrafos: [
      'Em cima: a data e o título (pode mudar).',
      'Receitas a produzir: cada linha com o formato, recheio, kg e unidades. Toque no nome para abrir a receita.',
      'Ingredientes necessários: o total já com o recheio incluído, e quantos sacos comprar.',
      '"Copiar relatório": copia um resumo em texto para colar onde quiser.',
      '"Adicionar à lista de compras": envia o que falta comprar para a Lista de compras.',
      '"Concluir produção": dá baixa dos ingredientes no stock e dá entrada dos produtos acabados. Pede confirmação.',
    ],
  ),
  HelpTopic.compras: (
    titulo: 'Lista de compras',
    paragrafos: [
      'O que precisa de comprar, agrupado por fornecedor.',
      'Cada linha mostra quantos sacos comprar, o peso da embalagem, quanto precisa e o preço estimado.',
      'Em cima vê o total esperado, o que já foi comprado e o que ainda falta.',
      'Marque a caixa quando comprar — a quantidade entra logo no inventário certo.',
      'Botão "+": primeiro escolhe se é um "Ingrediente" (escolhe da lista, quantidade em g/kg → entra no stock de ingredientes) ou "Material da loja" (equipamento, consumível, mobiliário, ferramenta, limpeza… — dá-lhe um nome, categoria, quantidade e unidade → entra no inventário "Outros"). Pode deixar uma nota.',
      'Ao escolher um ingrediente que já compras a mais do que um fornecedor, aparece um aviso (💡) a dizer qual é o mais barato e quanto poupas — toca no ícone de informação (ⓘ) para ver a comparação completa entre todos os fornecedores, do mais barato ao mais caro, por kg/L/unidade.',
      'Menu (⋮): "Reorganizar lista" apaga os comprados e recalcula; "Limpar lista" apaga tudo. Ambos pedem confirmação.',
    ],
  ),
  HelpTopic.comprasRelatorio: (
    titulo: 'O que comprei',
    paragrafos: [
      'Mostra tudo o que deu entrada no stock por compra num período: quando dás o visto na lista de compras ou quando aplicas uma fatura com a ação de stock.',
      'Escolhe o dia, a semana, o mês ou o ano e agrupa por dia, por fornecedor ou por produto. O custo é estimado (quantidade × preço atual do produto); para o valor exato de cada compra, vê as Faturas.',
      'O ícone de descarregar guarda a lista num ficheiro CSV (abre no Excel). Este histórico não se apaga quando limpas a lista de compras.',
    ],
  ),
  HelpTopic.inventario: (
    titulo: 'Inventário — material da loja',
    paragrafos: [
      'O Inventário junta numa só página tudo o que a empresa compra e guarda, em quatro secções: Ingredientes, Limpeza e insumos, Material da loja e Embalagens. Troca de secção nos botões do topo; uma secção com itens abaixo do mínimo mostra "a acabar".',
      'Material da loja: o inventário geral — equipamentos, mobiliário, ferramentas… agrupado por categoria. O material que marcas como comprado na lista de compras aparece aqui automaticamente.',
      'Botão "Material": adicionar qualquer coisa da empresa que não seja ingrediente nem produto — uma tesoura, uma mesa…',
      'Chips de vista: "Tudo", "Favoritos" (a estrela em cada linha fixa os itens que queres ver primeiro) e "Mais usados".',
      'O triângulo de aviso aparece quando algo está abaixo do stock mínimo.',
      'Toca num item para dar entrada ou saída de stock e definir o mínimo. Toque longo: histórico de movimentos.',
      'Nos Ingredientes e na Limpeza e insumos o stock aparece em cada linha ("Stock 2,5 kg"): toca nele para dar entrada ou saída. Os cookies prontos contam-se na Contagem diária.',
    ],
  ),
  HelpTopic.faturas: (
    titulo: 'Faturas',
    paragrafos: [
      'Guarda aqui as faturas de compra e as listas de preços dos fornecedores.',
      'Botão "Nova fatura": escolhes se é uma fatura ou uma lista de preços, o fornecedor, e o ficheiro — uma foto tirada com o telemóvel (JPG/PNG) ou um PDF.',
      'A seguir uma IA lê as linhas (produtos, quantidades, preços). Podes sempre corrigir antes de aplicar.',
      'Cada fatura é única: se carregares a mesma outra vez (mesmo fornecedor e número, ou mesma data e total), fica marcada como duplicada e não é aplicada.',
      'O ficheiro é guardado com o nome FT-FORNECEDOR-DDMMAAAA (a data da fatura), para organização e futura exportação para a contabilidade.',
      'As faturas ficam agrupadas por mês. Toca e mantém numa fatura para a corrigir, ver o histórico ou apagar — o proprietário e os administradores podem fazê-lo mesmo depois de aplicada.',
      'O estado mostra: Nova, Analisada (IA leu), Confirmada (já aplicada), Erro ou Ignorada. Os chips por baixo da pasta filtram por estado (só aparecem quando há mais do que um estado presente).',
      'O botão de ordenar (seta) organiza por Data, Fornecedor ou Valor — dentro de cada mês (os meses continuam sempre do mais recente para o mais antigo).',
      'Ícone da lista (☑): escolhe várias faturas de uma vez para marcar como "Ignorada" — útil para faturas antigas de que só queres guardar o ficheiro digitalizado, sem validar preços nem stock.',
      'Ícone da pasta (canto superior): resumo do mês para a contabilidade — lista, total e "Copiar resumo (CSV)". O envio mensal por email é automático se estiver configurado no servidor.',
      'Se ligares um scanner à pasta configurada no servidor, as faturas entram sozinhas (aparecem como "Nova" com a nota "Scanner: …").',
      'Menu (⋮, só proprietário/administrador): "Limpar vazias, com erro e sem linhas" e "Faturas apagadas" (para restaurar).',
    ],
  ),
  HelpTopic.faturaRevisao: (
    titulo: 'Rever fatura',
    paragrafos: [
      'Confere cada linha que a IA leu. A imagem da fatura fica visível (ao lado, em ecrã grande; por cima, no telemóvel — toca para ampliar; "Ocultar fatura" dá mais espaço às linhas). PDF abre à parte.',
      'Cada linha tem 5 tipos: Ingrediente, Embalagem, Limpeza / insumo, Bebida e Revenda (estes três últimos ficam todos em "Limpeza e insumos" — só muda a categoria sugerida). Escolhe o que a linha é antes de a ligar.',
      'Toca em "Ingrediente" para ligar a linha ao ingrediente certo (já vem pré-escolhido pelo nome mais parecido) ou escolhe "Criar ingrediente novo".',
      'Numa linha de Embalagem: o "Tipo" e, numa linha de Bebida/Revenda, a "Categoria" são texto livre — escreve um novo se o que precisas não estiver nas sugestões. "Peças compradas" (só embalagens) já vem preenchido pela quantidade que a IA leu (ex. rolo de 500 adesivos) — antes tinhas de corrigir isto depois em Embalagens. Em "Formatos de cookie" da embalagem, "+ Novo formato" cria um formato só com o nome (completa o peso depois em Configurações → Formatos de cookie).',
      'Se o ingrediente da fatura é o mesmo que já tens com outro nome (ex.: a fatura diz "Limão cal 3/4" e tu tens "Limão siciliano"), marca "Passar a chamar-se…": o ingrediente é renomeado e a mudança aplica-se a todas as receitas e fichas que o usam.',
      '"Comprado" é a quantidade que entra no stock; "Preço embalagem" e "Embalagem" atualizam o preço por grama do ingrediente.',
      'Ação por linha: Preço (só atualiza o preço), Stock (só dá entrada), Preço + Stock, ou Ignorar (ex.: uma linha duplicada — a IA por vezes lê a mesma linha duas vezes).',
      'Falta algum ingrediente na lista que a IA leu? Usa "Adicionar item em falta" para o escreveres à mão. Uma linha a mais, errada ou duplicada? O ícone de remover tira-a da lista (fica como "Ignorar" ao aplicar — nunca mexe em nada com ela).',
      'O preço só muda se esta fatura for igual ou mais recente do que a última atualização de preço desse ingrediente. Se carregares uma fatura antiga, a entrada de stock é feita à mesma, mas o preço mantém-se (fica sempre o do documento mais recente).',
      '"Aplicar aos ingredientes" grava tudo: os preços recalculam os custos das receitas e fichas em cascata.',
    ],
  ),
  HelpTopic.vendas: (
    titulo: 'Vendas',
    paragrafos: [
      'Regista aqui o que foi vendido — a base do painel financeiro, do DRE e da análise de sabores mais vendidos.',
      'Ícone da nuvem (canto superior): sincroniza com o Vendus — traz as vendas novas desde a última vez, emparelhadas automaticamente com as fichas técnicas pelo nome. Só funciona se a chave do Vendus estiver configurada no servidor; se houver linhas sem correspondência, aparece um aviso no resumo.',
      '"Reimportar histórico (escolher data)" (no mesmo ícone da nuvem): volta a pedir ao Vendus as vendas num intervalo de datas à escolha (desde/até), em vez de continuar de onde a última sincronização ficou — útil para trazer vendas mais antigas que ainda não estão na app.',
      '"Registar venda": escolhe a data e adiciona linhas — um produto (ficha técnica, com o preço já sugerido) ou um item livre (texto), quantidade e preço.',
      'Ícone de importar (canto superior): carrega um ficheiro .csv com colunas data, produto, quantidade, preço. Cada linha é ligada automaticamente à ficha técnica com o nome mais parecido; sem correspondência clara, fica só com a descrição (aparece com um aviso na venda).',
      'Define o "Preço de venda" de cada produto na sua Ficha Técnica — fica disponível como sugestão ao registar vendas e mostra a margem sobre o custo.',
      'O botão de ordenar (seta) organiza por Data ou Valor; os chips por origem (Manual/CSV/Vendus, quando há mais do que uma) filtram a lista.',
      'Toca numa venda para ver as linhas e, se precisares, apagá-la. Aí também defines o canal de venda (loja física, Uber Eats, Glovo, Bolt Food, parceria Alvalade, revenda, envio nacional, eventos…) e o método de pagamento — usados no Relatório geral do Painel financeiro para ver margens por canal. As vendas do Vendus ficam como "Loja física" por omissão e podem ser corrigidas.',
      'As vendas do Vendus passam a guardar também a hora, o método de pagamento e o valor sem IVA de cada linha. Para preencher isto nas vendas antigas, usa "Reimportar histórico" com o intervalo que queres completar.',
    ],
  ),
  HelpTopic.analiseVendas: (
    titulo: 'Análise de vendas',
    paragrafos: [
      'Mostra o que se vendeu por sabor/produto (ficha técnica) no período escolhido: quantidade, receita e a margem real (com base no custo guardado em cada venda, não no custo atual).',
      '"Mais vendido" é o que teve mais unidades; "Maior margem" é o que deu mais lucro por cada euro vendido — não são sempre o mesmo produto.',
      'A seta ao lado de cada linha compara a quantidade vendida com o período anterior de igual duração — sobe ou desce a dizer se aquele sabor está a vender mais ou menos.',
      '"Sem produto identificado" junta as linhas de venda que não foram ligadas a nenhuma ficha técnica (ex.: de uma importação de CSV sem correspondência) — não têm margem calculada.',
    ],
  ),
  HelpTopic.encomendas: (
    titulo: 'Encomendas',
    paragrafos: [
      'Regista aqui os pedidos dos clientes para uma data e hora específicas — diferente das Vendas, que é o registo do que já foi vendido/pago.',
      'Cada encomenda tem produtos (fichas técnicas) com quantidade, e passa pelos estados Nova → Em produção → Pronta → Entregue (ou Cancelada, em qualquer altura).',
      '"Encomendas por vir" no Início destaca as que faltam menos horas do que o configurado (ícone de engrenagem em Encomendas) — fica vermelho quando falta menos de 1 hora.',
      'Ícone de impressora no detalhe da encomenda: abre o talão para imprimir na fábrica, com a data/hora bem grande para não passar ao lado. O tamanho do talão (térmico 80mm ou A4) e se deve imprimir sozinho ao criar também se configuram ali.',
      'Sem impressora na fábrica? A lista de encomendas em si já serve — abre bem num tablet.',
      'O "Valor total" é sugerido automaticamente a partir do preço de venda das fichas técnicas escolhidas, mas pode ser editado ou deixado em branco. "Registar pagamento" guarda quanto já foi pago — a encomenda mostra Por pagar/Pago parcialmente/Pago, e isso também aparece no talão impresso (que acompanha a encomenda até ao cliente).',
      'Menu (⋮) no detalhe da encomenda: Editar (cliente, data/hora, produtos, valor), Registar pagamento, Cancelar ou Apagar.',
      'O botão de ordenar (seta) organiza por Data/hora ou Cliente; o chip "Urgentes" (quando há alguma) filtra só as que faltam menos horas do que o configurado.',
    ],
  ),
  HelpTopic.contagem: (
    titulo: 'Contagem diária',
    paragrafos: [
      'Para saberes, em cada local (a Loja, Alvalade, as Plataformas…), quantos cookies tinhas, assaste, venderam, foram para o lixo e quantos sobraram — por sabor e por dia.',
      'Separador "Rápido" (o do dia a dia): cada sabor tem um botão de menos, o número e um botão de mais (também podes escrever o número). Há três passos: Abrir, Dia e Fechar.',
      'Abrir: conta o que tens ao abrir. Vem preenchido com o que ficou de ontem; se ontem ninguém contou o fecho, a app calcula o que devia ter ficado (assados − vendas − perdas) e avisa. Corrige o que for diferente e, se houve perdas ou consumo próprio ontem, usa "Registar perdas de ontem".',
      'Dia: as vendas vêm sozinhas do Vendus. Em "Perdas e consumo próprio" escolhe o motivo (queimado, quebrado, fora do prazo, consumo próprio dos colaboradores…), põe as quantidades e regista. "Enviar / devolver" passa cookies de um local para outro (ex.: da Loja para Alvalade).',
      'Fechar: o número pequeno é o que devia haver pelas contas. Ajusta ao que realmente sobrou — a app mostra "faltam" ou "sobram". Se estiver tudo certo, "Está tudo como devia haver". Se não fechares, no dia seguinte a abertura já vem com o que devia ter ficado.',
      'Duas opções de trabalho (escolhes em cada aparelho): Opção 1 — contas a abertura e o fecho e as vendas vêm do Vendus. Opção 2 — como a 1 e ainda registas cada fornada: escolhe os sabores e quantidades e carrega em ASSAR. Cada sabor tem o seu cronómetro com o tempo de assadura da ficha técnica: vês quanto passou, quanto falta e uma barra de progresso. Quando um sabor está pronto o telemóvel vibra e toca e aparece "Tirei" nesse sabor (os outros continuam a contar). O que está no forno também aparece no Início. "Foi engano" cancela a fornada e apaga os assados.',
      'Os "Vendidos" vêm das Vendas, pelo canal de cada venda (ex.: "Parceria Alvalade" conta para Alvalade; "Uber Eats" para as Plataformas). Vendas sem canal ou com um canal que não está em nenhum local contam para a Loja. Os canais de cada local mudam-se no ícone dos locais.',
      'Separador "Detalhe": todas as contas de cada sabor (Abertura + Assados + Recebidos − Enviados − Vendidos − Desperdício = "Devia haver"), os registos do dia e o apagar de registos.',
      'Ícone do gráfico: o desperdício por motivo, sabor e local, ordenado pelo que custa mais (€ de matéria-prima e unidades), com a percentagem dos assados, o que era evitável (queimado, fora do prazo, quebrado, erro de produção — a degustação e o consumo próprio são escolhas), a comparação com o período anterior e uma dica para a maior perda evitável e o balanço de cada local — por exemplo, quantos cookies foram para Alvalade, quantos voltaram e quantos se venderam.',
    ],
  ),
  HelpTopic.haccp: (
    titulo: 'HACCP — segurança alimentar',
    paragrafos: [
      'Aqui registas o que a segurança alimentar pede: temperatura do frigorífico e da arca, limpezas, controlo de pragas (incluindo ocorrências) e validades como o extintor. Cada registo fica com data, hora e quem o fez — serve de prova numa fiscalização.',
      'Separador "Hoje": o que falta fazer. Vermelho = atrasado ou nunca registado; laranja = fazer hoje; verde = em dia. Toca em "Registar" no controlo.',
      'Temperaturas: escreve o valor medido. Se estiver fora dos limites do controlo (ex.: frigorífico 0 a 5 °C), fica logo como não conformidade e pede a ação corretiva. Nos outros controlos, desliga o interruptor se algo não estiver bem (ex.: viste sinais de pragas) e descreve o que fizeste.',
      'As não conformidades ficam em "Hoje" até as marcares como resolvidas. Nada se apaga: o histórico fica sempre para auditoria.',
      'Manutenções e validades (extintor, empresa de pragas): ao registar, indica a data da próxima revisão — o lembrete usa essa data.',
      'Separador "Registos": escolhe o período (hoje, 7 dias, este mês, mês passado…) e o tipo de controlo (temperatura, limpeza, pragas, manutenção, outros) e vê os registos. "Gerar relatório" cria o relatório formal desse período e tipo (ou de todos), numerado (HACCP-2026-0007), pronto a imprimir ou guardar em PDF. Na aba Hoje há o atalho "Relatório de hoje".',
      'O relatório tem: identificação do operador, período, quadro de cada controlo (limite crítico, valores, quem registou), cobertura (registos feitos face aos esperados), não conformidades com a ação corretiva, o enquadramento legal (Reg. (CE) n.º 852/2004, Reg. (CE) n.º 178/2002, DL n.º 113/2006), campos de assinatura do responsável e um código de integridade. O número e o código ficam guardados na emissão. O relatório é um registo dos controlos; a sua validade como evidência depende do plano HACCP do estabelecimento, validado pelo responsável.',
      'Separador "Controlos": cria, edita ou arquiva controlos e define a frequência (diária, semanal, mensal, anual, ocasional) e os limites de temperatura. "Adicionar os controlos habituais" cria uma lista de partida.',
    ],
  ),
  HelpTopic.colaboradores: (
    titulo: 'Equipa, cartões e quiosque de tarefas',
    paragrafos: [
      'O quiosque é um ecrã para o telemóvel que fica na loja ou na fábrica com a app sempre aberta. Mostra só os botões das tarefas diárias (limpezas, temperaturas, pragas, lote…): cada pessoa encosta o seu cartão NFC, toca num botão e fica feito — o registo guarda o nome e a hora.',
      'Chegas aqui pelo HACCP (ícone do cartão) ou pelo quiosque. Estão aqui todas as pessoas da Equipa (as contas da empresa — não é preciso criar nada) e, se quiseres, pessoas sem conta ("Pessoa sem conta"). Associa o cartão de cada uma: menu (⋮) → "Associar cartão" e encosta o cartão à parte de trás do telemóvel. Se não houver leitor NFC, escreve o número de série. Cada cartão só pode ser de uma pessoa. "Esconder do quiosque" tira alguém da lista sem apagar nada. O nome de quem é da Equipa muda-se na conta.',
      'Sem cartão (esqueceu-se dele): no quiosque toca no teu nome na lista.',
      'As tarefas vêm do HACCP → Controlos. Limpeza e manutenção: um toque. Temperatura: teclado grande (fora dos limites pergunta o que foi feito). Pragas: "Tudo bem" ou "Vi sinais". Outros (ex.: registo de lote): escreve o texto.',
      'Reabrir sem ligação: depois de abrires a app uma vez com rede, o telemóvel guarda-a; se o Wi-Fi cair e a página recarregar, a app abre na mesma, com a sessão iniciada (só pede a entrada de novo se o servidor recusar a sessão). Abre-a uma vez com rede depois de cada atualização.',
      'Sem ligação: se o Wi-Fi cair com o quiosque aberto, ele continua a funcionar. A lista de tarefas e das pessoas vem da última vez que houve ligação (aparece um aviso), cada toque fica guardado neste aparelho com a hora real ("N por enviar" no topo) e é enviado sozinho de 20 em 20 segundos quando a ligação voltar — ou toca no aviso para tentar já. Mantém a página aberta: se a recarregares sem ligação, não abre. Os registos guardados só existem neste aparelho até chegarem ao servidor.',
      'O quiosque volta sozinho ao ecrã do cartão 45 segundos depois do último toque. Para sair dele, mantém premido o cadeado (canto superior direito).',
      'Leitura de cartões: só funciona no Chrome do Android e com a app aberta por HTTPS. Na primeira vez o navegador pede permissão para o NFC.',
    ],
  ),
  HelpTopic.contabilidade: (
    titulo: 'Contabilidade',
    paragrafos: [
      'Os números da empresa numa só página, em secções: Resumo (entradas, saídas e lucro), DRE, Custos fixos, Equipamentos, Números mágicos e Relatórios e IVA. Toca na secção para mudar; o ? no canto explica a que estás a ver.',
      'Relatórios e IVA: escolhe o período e vê o IVA a separar (cobrado nas vendas menos o das faturas de compra). Daqui também sais para o Relatório geral (Excel/CSV, só administradores), as faturas do mês para a contabilista, "O que comprei", a Análise de vendas e os Relatórios HACCP.',
    ],
  ),
  HelpTopic.custosFixos: (
    titulo: 'Custos fixos',
    paragrafos: [
      'Regista aqui os custos reais que saem todos os meses: aluguel, salários, seguros, subscrições, etc.',
      'Isto é diferente dos percentuais em Configurações → Percentuais de custo: aqueles só servem para sugerir o preço de venda a partir do custo de matéria-prima. Aqui é o valor real, para o painel financeiro e o DRE.',
      'FIXO é o custo que NÃO conseguimos eliminar sem fechar ou mudar a estrutura do negócio: paga-se mesmo que não se venda nada. Exemplos: renda, salários da equipa, seguros, contabilista, licenças e taxas obrigatórias, empréstimos, internet e telefone essenciais, água/luz/gás de base. Por isso são os que têm de estar sempre cobertos.',
      'VARIÁVEL é o custo que podemos REDUZIR ou CORTAR — por um período ou para sempre — para a empresa não quebrar, e/ou que sobe e desce com a produção e as vendas. Exemplos: marketing e publicidade, subscrições e apps não essenciais, comissões de plataformas, entregas, embalagens e consumíveis comprados conforme as vendas, formações, consumo extra de energia do forno, horas extra. Quando o dinheiro aperta, é por aqui que se começa.',
      'Porque separar? Porque os dois pedem decisões diferentes: o fixo planeia-se e renegocia-se (e define a "venda mínima" dos Números mágicos); o variável vigia-se todos os meses e corta-se ou reduz-se quando preciso. Na dúvida, pergunta: "se for preciso, consigo cortar ou reduzir isto de forma relevante sem fechar?" — se sim, é variável; se não, é fixo.',
      'Ícone das faíscas (✨, canto superior): a IA lê os teus custos e sugere, para cada um, se é fixo ou variável e porquê — e, nos variáveis, o que fazer se apertar (reduzir, pausar ou cortar). Tu escolhes quais sugestões aplicar; nada muda sem confirmares.',
      '"Dia de pagamento" (opcional): o dia do mês em que pagas este custo. Se estiver preenchido, aparece um aviso "Pagamentos por vir" no Início quando faltar uma semana ou menos.',
      'Ícone de nuvem/upload (canto superior): importa vários custos de uma vez a partir de um ficheiro .csv com as colunas nome, valor mensal e (opcional) dia de pagamento.',
      'Equipamentos (forno, balcão, computadores…) têm a sua secção ao lado: a depreciação mensal deles entra automaticamente como despesa, sem precisar de criar um custo fixo à parte.',
      'Arquivar mantém o histórico sem contar no total atual; só apagar remove por completo.',
    ],
  ),
  HelpTopic.equipamentos: (
    titulo: 'Equipamentos',
    paragrafos: [
      'Cada peça de equipamento da loja (forno, balcão, computador, vitrine…) com o preço de compra e a vida útil em anos.',
      'A "depreciação mensal" é o preço de compra dividido pela vida útil em meses — é o desgaste do equipamento, em euros por mês. Soma-se automaticamente ao painel financeiro, ao DRE e aos Números mágicos como despesa, sem precisar de a registar outra vez em Custos fixos.',
      'Ícone de upload (canto superior): importa vários equipamentos de uma vez a partir de um ficheiro .csv com as colunas nome, custo e vida útil (anos).',
      'Não é preciso substituir nada quando o equipamento acaba a vida útil — arquiva-o e cria o novo, se for o caso.',
    ],
  ),
  HelpTopic.numerosMagicos: (
    titulo: 'Números mágicos',
    paragrafos: [
      'Mostra a partir de quanto vendido, por mês (e por dia), tudo já está pago — custos fixos, variáveis, depreciação dos equipamentos, imposto e o custo da matéria-prima (CMV). A partir daí, cada euro vendido a mais continua a levar imposto e CMV; só o que sobra depois disso é lucro líquido.',
      'Os percentuais de Imposto e CMV vêm de Configurações → Percentuais de custo — muda-os lá se precisares.',
      'A "venda mínima" é sempre um valor mensal cheio; o cartão de baixo compara com o que já vendeste no período escolhido, para veres se estás perto ou longe do objetivo.',
      'Períodos: o Dia é um único dia (a venda mínima desse dia contra o que vendeste nesse dia), a Semana vai de domingo a sábado (ignora o mês), o Mês vai do dia 1 ao último dia e o Ano de 1 de janeiro a 31 de dezembro. Na semana e no mês há uma lista "Dia a dia" com o vendido de cada dia contra a venda mínima diária. São sempre contados inteiros — por isso o mínimo do período não muda de um dia para o outro; só o "vendido" vai subindo. As datas exatas aparecem por baixo do nome do período; usa as setas para ver semanas/meses anteriores (toca nas datas para saltar para um dia).',
      'Se o aviso de percentuais aparecer, é porque Imposto + CMV somam 100% ou mais — nesse caso não há venda que cubra os custos só com esses dois; revê os valores em Configurações.',
    ],
  ),
  HelpTopic.painelFinanceiro: (
    titulo: 'Painel financeiro',
    paragrafos: [
      'Junta as Vendas e os Custos fixos num só sítio: quanto entrou, quanto saiu e o lucro, por semana ou mês.',
      '"Custo dos produtos vendidos" é o custo real da matéria-prima do que foi vendido (guardado em cada venda no momento em que foi registada).',
      '"Distribuição teórica" mostra, com as percentagens atuais de Configurações → Percentuais de custo, para onde o valor vendido deveria ir (matéria-prima, salário, aluguel...). É um modelo, não o dinheiro que saiu de verdade — isso são os Custos fixos, mostrados por cima.',
      'A seta ao lado de cada número compara com o período anterior (a semana anterior, ou o mês civil anterior). O Dia é um único dia, a Semana vai de domingo a sábado, o Mês do dia 1 ao último dia e o Ano de 1 de janeiro a 31 de dezembro; as datas exatas aparecem por cima e as setas levam-te a períodos passados.',
      'Se houver vendas sem produto identificado (ex.: de uma importação de CSV), o custo delas não é conhecido — aparece um aviso e o lucro fica sobrestimado nessa medida.',
      'Relatório geral (secção "Relatórios e IVA", só administradores): gera o Relatório geral num ficheiro Excel (.xlsx, uma folha por relatório) ou em CSV (.zip), para os últimos 12 meses (ou 6, ou este ano, ou o período do painel). Inclui resumo mensal, vendas por canal e sabor, produção, custo por sabor (com histórico de preços de compra), despesas por categoria e tesouraria. As folhas que a app ainda não regista (plataformas de entrega, pessoal, eventos, origem dos clientes) vão como modelos por preencher; a folha "Leia-me" diz o que está completo. Margens são sem IVA: o valor sem IVA vem do Vendus quando existe, ou estima-se com a taxa que escolheres.',
      '"IVA a separar": o IVA cobrado nas vendas menos o IVA das faturas de compra confirmadas = o que há a entregar ao Estado (ou crédito de IVA, se as compras tiveram mais). Vê-se por dia, semana, mês ou ano, e há uma lista "Dia a dia". O IVA das vendas vem do Vendus quando existe; senão estima-se com a taxa "IVA das vendas" que defines em Configurações → Percentuais de custo. Reserva este valor: não é lucro teu.',
      '"Dicas para melhorar" (só administradores): toca em "Gerar dicas com IA" e a IA lê os números do período mostrado e do anterior (receita, lucro, custos fixos e variáveis, CMV, imposto) e sugere o que atacar. Faz isto no fim de cada semana ou mês para ir melhorando. São sugestões geradas por IA — avalia antes de agir. Os fixos não se eliminam; os variáveis podem reduzir-se ou cortar-se.',
    ],
  ),
  HelpTopic.dre: (
    titulo: 'DRE',
    paragrafos: [
      'DRE = Demonstração de Resultados do Exercício: o mesmo cálculo do painel financeiro, mas no formato de relatório clássico de contabilidade (receita → custo → lucro bruto → despesas → resultado).',
      'Escolhe a semana (domingo a sábado), o mês (dia 1 ao último dia) ou o ano, navega pelas setas até ao período que queres e toca no ícone de impressão para abrir uma versão simples para imprimir ou guardar como PDF.',
      'Se houver vendas sem produto identificado, o custo delas não entra no cálculo e aparece um aviso — o resultado fica sobrestimado nessa medida.',
    ],
  ),
  HelpTopic.produtos: (
    titulo: 'Informação do produto',
    paragrafos: [
      'Tudo o que o cliente (e a fiscalização) precisa de saber sobre o produto, pronto a copiar ou imprimir: declaração nutricional, lista de ingredientes e alergénios, peso, validade e conservação.',
      'Chega-se aqui pelo ícone do prato, no topo da ficha técnica. Na lista de fichas, o prato vermelho ao lado do nome diz que falta completar a informação (e o filtro "Informação por completar" mostra só essas).',
      'A lista de ingredientes segue as regras da UE: por ordem decrescente de peso e com os alergénios a negrito. É calculada sozinha a partir da ficha técnica, das receitas e dos ingredientes. "Completa" usa o nome de cada ingrediente; "Resumida" usa nomes curtos, para etiquetas pequenas.',
      '"Falta completar" mostra o que ainda não está preenchido: nutrição de algum ingrediente, prazo de validade e modo de conservação. "Corrigir a nutrição" leva-te ao ingrediente em falta; "Preencher os dados" abre a ficha.',
      'Ícone da impressora: imprime a etiqueta (completa ou resumida) com a informação nutricional. Ícone de copiar: junta tudo num texto.',
    ],
  ),
  HelpTopic.tabelaRevendedores: (
    titulo: 'Tabela de preços para revendedores',
    paragrafos: [
      'Faz a tabela de preços que mandas a quem revende os teus produtos. Cada produto com preço de venda entra com o preço por unidade sem IVA e com IVA (o IVA das vendas está em Configurações).',
      'Como se chega ao preço: "Desconto sobre o preço ao público" tira uma percentagem ao preço de venda sem IVA; ou escolhe um canal (o revendedor ou plataforma que criaste na ficha técnica) e o revendedor paga o que te chega com as taxas desse canal tiradas — a mesma conta da Rentabilidade.',
      'Desconto por quantidade: junta degraus ("a partir de 24 unidades, −5 %"). O desconto aplica-se por produto e cada degrau aparece como uma coluna na tabela. Toca no × de um degrau para o tirar.',
      'Copiar e WhatsApp dão a tabela em texto (o WhatsApp abre a conversa e deixa o texto copiado, caso a mensagem venha cortada); PDF abre a impressão do navegador, onde escolhes "Guardar como PDF".',
      'Desmarca os produtos que não queres mostrar ao revendedor. O desconto, o canal, os degraus e os produtos escolhidos ficam guardados neste aparelho.',
    ],
  ),
  HelpTopic.previsaoAssar: (
    titulo: 'Quantos assar',
    paragrafos: [
      'Diz-te, sabor a sabor, quantas unidades convém ter prontas hoje, amanhã ou num dos próximos dias de trabalho. Serve para assar o que se vende e não deitar fora o que sobra. Os dias de folga (Configurações → Dias de trabalho) não aparecem. Em "Hoje" desconta-se o que já se vendeu hoje e o stock que ainda há.',
      'Como calcula: olha para as últimas 12 semanas, só os dias iguais ao que escolheste (as quintas-feiras, por exemplo) em que a loja vendeu. Para cada sabor testa quatro modelos — mais peso às últimas semanas, média, mediana e "igual à semana passada" — nos dias já passados, e usa o que errou menos. O ponto colorido mostra a confiança: vermelho = pouco histórico, laranja = razoável, verde = bom.',
      'A margem de segurança (um pouco acima do previsto, para não faltar) vem do erro desse modelo. Nos sabores que costumam ir para o lixo (5 % ou mais do que se faz, medido pelo Desperdício da Contagem) a margem encolhe e a partir de 15 % desaparece.',
      '"Descontar o que já há em stock" tira o que ainda tens nos locais (contagem de fecho de hoje, ou a estimativa pelas contas). O total mostra também as fornadas, pela média das tuas fornadas dos últimos 60 dias.',
      'As vendas vêm do Vendus automaticamente (o servidor sincroniza de hora a hora). Por baixo do título vês quando foram atualizadas; se tiverem mais de 3 horas, a app atualiza-as sozinha ao abrir esta página, e o botão ↻ atualiza já. Se o Vendus deixar de sincronizar durante mais de um dia, aparece um aviso no Início e no resumo diário.',
      '"Agendar produção para …" cria na Agenda a produção desse dia com as quantidades da lista (os produtos sem receita de massa ligada ficam de fora). "Como a previsão tem acertado" refaz a previsão dos últimos 7 dias de venda e compara com o que se vendeu, para saberes quanto podes confiar nela.',
      'Lista de compras: ao agendar, a app prepara também a lista do que falta comprar para essa produção, contra o stock de hoje, e diz quantos ingredientes faltam e quanto custam (≈). Para cada ingrediente sugere a marca/fornecedor mais barato ao kg (preços dos últimos 150 dias), a não ser que a receita fixe um produto. Desmarca "Preparar também a lista de compras" se preferires só agendar; "Ver compras" abre a lista.',
      'O ajuste do dia (−20 %, +20 %, +50 % evento) sobe ou desce tudo de uma vez: a app não sabe de feriados, chuva ou encomendas especiais. Com mais semanas de vendas a previsão acerta melhor — no início, com pouco histórico, trata-a como uma sugestão. Precisa de vendas ligadas a fichas técnicas (Vendus ou importação).',
    ],
  ),
  HelpTopic.pessoasFormacoes: (
    titulo: 'Formações e certificados',
    paragrafos: [
      'Guarda aqui os certificados e formações de cada pessoa — manipulador de alimentos, HACCP, primeiros socorros, ficha de aptidão… — com a data, a validade e o ficheiro (PDF ou foto). Em "Nova formação" escolhes a pessoa, tocas numa sugestão de título e na validade (+1, +2, +3 ou +5 anos) e anexas o certificado: tudo em poucos toques.',
      'A app avisa 30 dias antes de caducar: aparece o cartão "Formações a caducar" no Início e uma secção no resumo diário (email/Telegram). Se renovares, regista o novo certificado: só o mais recente de cada título conta e o antigo deixa de avisar.',
      'Renovar: os certificados a caducar ou caducados aparecem primeiro, cada um com o botão "Renovar". Abre o formulário já preenchido (mesma pessoa, título e entidade, feito hoje e com o mesmo prazo de validade que o anterior): só tens de anexar o certificado novo e guardar.',
      'Toca numa linha para editar (ou apagar) e no clipe para abrir o ficheiro. É um dado pessoal: cada pessoa só vê os seus; a administração vê os de toda a equipa e regista para qualquer pessoa.',
    ],
  ),
  HelpTopic.pessoasNotas: (
    titulo: 'Notas da equipa',
    paragrafos: [
      'Um quadro de anotações partilhado: deixa um recado para os colegas, regista uma ocorrência (algo que se avariou, uma reclamação, um acidente) ou cria um lembrete.',
      'Tipos: Recado, Ocorrência e Lembrete. Num lembrete escolhes o dia: a partir desse dia a nota aparece no Início ("Notas para hoje") até a arquivares. "Fixar" põe a nota no topo; "Arquivar (já tratada)" tira-a da lista sem a apagar (vês em "Arquivadas" e podes voltar a abri-la).',
      'Toda a equipa (menos a Leitura) vê as notas e pode fixá-las ou arquivá-las; só quem escreveu a nota (ou a administração) altera o texto ou a apaga. Não ponhas aqui palavras-passe nem dados pessoais sensíveis.',
    ],
  ),
  HelpTopic.pessoasFerias: (
    titulo: 'Mapa de férias e ausências',
    paragrafos: [
      'Aqui pedes férias, vês o saldo de dias e quem está fora em cada dia. "Pedir férias" → escolhe as datas → o pedido fica "Por aprovar" até o proprietário ou um administrador o aprovar (ou recusar). Podes apagar um pedido teu que ainda não foi decidido.',
      'Os dias contam-se como a lei manda: dias úteis, de segunda a sexta, sem feriados nacionais (a app sabe a Páscoa e os feriados móveis; feriados municipais não entram). O direito por omissão é 22 dias úteis por ano; a administração muda o de cada pessoa em "Direito a férias" (por exemplo, no ano de entrada). "Restam" desconta os dias gozados e os pedidos pendentes.',
      'O mapa do mês mostra uma linha por pessoa e um quadrado por dia: verde = férias, verde claro = por aprovar, laranja = baixa, vermelho = falta; os fins de semana e feriados ficam mais escuros. Toda a equipa vê as férias aprovadas dos colegas; as baixas e faltas só as vê a própria pessoa e a administração (são dados pessoais).',
      'A administração também regista ausências de qualquer pessoa (férias, baixa, falta) com "Registar férias / ausência" e imprime o "Mapa de férias" do ano. A lei pede que o mapa seja elaborado até 15 de abril e fique afixado até 31 de outubro. A app avisa quando os períodos se sobrepõem para a mesma pessoa.',
    ],
  ),
  HelpTopic.pessoasEscala: (
    titulo: 'Escala semanal (mapa de horário)',
    paragrafos: [
      'Mostra, semana a semana, quem trabalha e a que horas. Cada pessoa vê o seu horário no cartão "O meu horário".',
      'Para a administração: toca no nome de alguém e define o horário habitual — marca os dias em que trabalha, as horas de entrada e saída e a pausa ("Igual ao primeiro dia marcado" copia as horas). Faz isto uma só vez por pessoa: a escala de todas as semanas fica feita. Para um dia especial, toca nesse dia: outro turno ou folga só nesse dia (fica com uma moldura e "(alterado)"); "Voltar ao habitual" desfaz.',
      'A escala respeita as férias, baixas e faltas aprovadas (aparecem a verde/laranja) e os dias em que a empresa não trabalha (Configurações → Dias de trabalho, "—").',
      'No Ponto, ao lado das horas de cada pessoa passa a aparecer as horas previstas e o saldo (horas a mais ou a menos) até ontem; no quiosque, depois de encostar o cartão, aparece o horário de hoje. "Imprimir o mapa de horário" faz a folha da semana para afixar (a lei pede o mapa de horário de trabalho afixado).',
    ],
  ),
  HelpTopic.saudeDados: (
    titulo: 'Saúde dos dados',
    paragrafos: [
      'Mostra o que falta preencher para a Rentabilidade, o Quantos assar e as etiquetas ficarem certos, e a percentagem do que já está completo.',
      'Produtos sem preço de venda (não entram na Rentabilidade nem na tabela de revendedores), sem custo calculado (a ficha não tem ingredientes ou eles não têm preço), sem tempo de assadura (sem lucro por hora de forno) e sem temperatura do forno. Ingredientes comprados sem preço (o custo das fichas fica incompleto) e sem informação nutricional (a etiqueta fica incompleta). Os ingredientes de fabrico próprio não precisam de preço.',
      'Toca num produto para abrir a ficha e corrigir; "Resolve primeiro os de preços e custos" (a vermelho). Puxa para baixo para atualizar. Não é um aviso: só aparece aqui, quando quiseres ver.',
    ],
  ),
  HelpTopic.pessoasPonto: (
    titulo: 'Ponto da equipa',
    paragrafos: [
      'Registo de entrada, pausa e saída de cada pessoa. Marca-se aqui ("O meu ponto") ou no quiosque de tarefas, onde cada pessoa encosta o cartão e toca em Entrada, Pausa ou Saída — também funciona sem ligação (fica guardado e segue depois).',
      'O proprietário e os administradores veem todas as marcações: quem está a trabalhar agora e, por mês, as horas de cada pessoa (descontada a pausa). Toca numa pessoa para ver os dias; toca numa marcação para a corrigir (hora, tipo e motivo) ou apagar — a correção fica assinalada e guarda a hora original. "Marcação manual" serve para quando alguém se esqueceu de marcar. Os outros só veem as suas próprias marcações.',
      'Avisos a vermelho: "Falta a saída" (a jornada passa de 16 horas ou ficou de um dia anterior e não conta como trabalhada até se corrigir), "Pausa sem fim", saída sem entrada. "Copiar a folha do mês" dá o CSV (uma linha por jornada) para colar numa folha de cálculo ou enviar à contabilidade.',
      'Saída por marcar: se alguém entrou e não saiu (16 horas depois, ou uma hora depois do fim do turno da Escala), a administração vê um cartão no Início e um aviso no topo do Ponto, com "Saída às 16:30" para a registar num toque. O resumo diário também avisa.',
      'Atenção: a app regista as horas, mas não é um sistema certificado de assiduidade; confirma com a tua contabilista o que a lei exige (registo do tempo de trabalho e mapa de horário).',
    ],
  ),
  HelpTopic.rentabilidade: (
    titulo: 'Rentabilidade por sabor e canal',
    paragrafos: [
      'Mostra que produtos dão mais lucro. Escolhe o canal — Loja física ou uma plataforma/revendedor que criaste na ficha técnica (com as suas taxas) — e vê o ranking. O lucro é sem IVA, ao preço de venda que o produto tem hoje na ficha, depois das taxas do canal e dos custos da empresa (as percentagens de Configurações sobre o que chega a nós).',
      'Ordena por: Lucro por unidade; Lucro por hora de forno (lucro por unidade × unidades por fornada × 60 ÷ tempo de assadura — quanto renderia uma hora de forno cheia só com esse produto); ou Margem %. O número em baixo à direita é "€/h".',
      '"Un. por fornada": a app estima pela média das tuas fornadas dos últimos 60 dias; podes escrever outro valor (fica guardado neste aparelho). Precisa do tempo de assadura na ficha para o lucro por hora.',
      'A barra mostra o lucro por unidade (verde) ou o prejuízo (vermelho). Ficam de fora os produtos sem custo ou sem preço de venda. Não inclui a embalagem extra de plataformas.',
      'Usa isto para decidir o que promover, o que fazer menos em horas de forno apertadas, onde subir preço e que canais compensam.',
    ],
  ),
  HelpTopic.lotes: (
    titulo: 'Lotes e rastreabilidade',
    paragrafos: [
      'A lei (Reg. (CE) n.º 178/2002, art. 18.º) pede que saibas de onde vêm os ingredientes de cada coisa que vendes: se um fornecedor avisar que um lote tem um problema, tens de saber que produtos o levaram. Aqui registas isso em poucos toques.',
      '"Novo lote": escolhe o produto, a data, as unidades e (se a ficha tem prazo) a validade é calculada. Para cada ingrediente da ficha escolhes o lote que usaste (o que vence primeiro vem à frente) ou "＋ Novo lote…" e escreves o código que vem na embalagem do fornecedor e a validade. Se não souberes, "Sem lote" — o lote fica marcado com um aviso.',
      'Validades: os lotes cuja validade está a acabar (ingredientes: 5 dias; produtos: hoje e amanhã) aparecem no topo dos Lotes, num cartão no Início e no resumo diário. "Já usado" / "Vendido/retirado" tira o aviso desse lote. Só avisa de lotes que registaste com validade; vencidos há mais de 14 dias deixam de avisar.',
      'O lote recebe um código (ex.: 261006-ALB-1: data, produto e nº do dia). Na página do lote: "Etiqueta com QR" imprime a etiqueta com o lote e um QR que abre esta página no telemóvel (precisa de entrar na app); "Ficha" imprime/guarda em PDF a folha de rastreabilidade com os ingredientes, lotes e fornecedores.',
      'A lupa ao lado de cada ingrediente mostra todos os lotes de produção em que esse lote do fornecedor entrou — é a lista do que retirar em caso de alerta.',
      'Só o proprietário/administrador apaga lotes (rastreabilidade). Os lotes ficam registados mesmo que mudes os ingredientes da ficha depois.',
    ],
  ),
  HelpTopic.avisos: (
    titulo: 'Avisos e resumo diário',
    paragrafos: [
      'Recebe todos os dias, à hora que escolheres (hora de Lisboa), um resumo do que pede atenção: HACCP por fazer, stock baixo, pagamentos próximos (7 dias), faturas por rever e preços que subiram nas últimas 24 h, mais quem está ausente hoje (férias; baixas e faltas aparecem só como "ausente"). Escolhe o que incluir. Se estiver tudo em dia, recebes "Tudo em dia". Nos dias em que a empresa não trabalha (Configurações → Dias de trabalho) o resumo não é enviado, e o HACCP não pede tarefas nem conta esses dias como atraso.',
      'Por Telegram (grátis, instantâneo): fala com @BotFather no Telegram → /newbot e copia o token; cola-o aqui e guarda (fica cifrado no servidor e nunca volta a aparecer); abre o teu bot e envia /start; toca em "Detetar o meu chat" e escolhe o teu. Podes pôr o chat de um grupo (adiciona o bot ao grupo).',
      'Por email: precisa de o servidor ter o email configurado (PocketBase → Definições → Mail). Podes pôr vários endereços separados por vírgula.',
      'Resumo da semana: liga o interruptor e escolhe o dia (por omissão, segunda-feira). Na hora do resumo diário recebes como correu a semana anterior (segunda a domingo): vendas e a comparação com a semana anterior, a margem sobre a matéria-prima, o desperdício em euros (com o evitável à parte), as horas da equipa, os preços que subiram, quem vai estar ausente na semana seguinte e as formações a caducar. É enviado mesmo que o dia escolhido seja de folga. "Ver o resumo da semana passada" mostra-o já.',
      '"Enviar um teste" manda já o resumo para os canais ligados e mostra o resultado de cada um; sem canais ligados mostra só a pré-visualização.',
      'WhatsApp: o código existe mas está desligado (a API do WhatsApp Business é paga); só se ativa no servidor com GC_TURNKEY_WHATSAPP_TOKEN e GC_TURNKEY_WHATSAPP_PHONE_ID.',
    ],
  ),
  HelpTopic.aprovacoes: (
    titulo: 'Aprovações de contas',
    paragrafos: [
      'Qualquer pessoa pode criar conta, mas só entra depois de ser aprovada. Quem se regista fica no ecrã "A tua conta aguarda aprovação".',
      'Esta página (só para o operador da plataforma) lista as contas por aprovar. "Aprovar" deixa a pessoa continuar (criar a empresa dela); "Recusar" apaga o pedido — se quiser entrar, tem de se registar de novo.',
      'O operador é o proprietário mais antigo, ou os emails indicados na variável GC_TURNKEY_OPERADORES do servidor (separados por vírgula). Quando há contas à espera aparece um cartão "Contas por aprovar" no Início.',
      'Não precisas de abrir o painel de administração do PocketBase (/_/) para isto.',
    ],
  ),
  HelpTopic.variacoesPreco: (
    titulo: 'Variações de preço',
    paragrafos: [
      'Sempre que o preço de um ingrediente muda (por exemplo ao aplicar uma fatura), a app regista a variação e mostra aqui o que mudou: o preço por kg antes e depois, a variação em % e as fichas técnicas que ficaram mais caras ou mais baratas — com o custo e a margem antes e depois.',
      'Aviso: quando um preço sobe mais do que o limiar (por omissão 5 %; muda em Configurações → Percentuais de custo → "Avisar quando um preço sobe mais de"), aparece um cartão "Preços subiram" no Início e a secção Preços do Inventário mostra quantas subidas há por ver. "Marcar como vistas" limpa o aviso neste aparelho.',
      'Toca numa variação para ver as fichas afetadas. Usa isto para decidir se subes o preço de venda, trocas de fornecedor ou renegocias. As variações ficam guardadas cerca de 4 meses.',
      'As margens são sobre o preço sem IVA (o IVA soma-se no fim) e só aparecem nas fichas com preço de venda.',
      'Sugestão de preço: se o custo de uma ficha subiu, aparece "Sugestão: €X para a margem voltar a Y%" — o preço que mantém a margem que tinhas, com IVA e arredondado para cima aos 5 cêntimos. "Aplicar" muda o preço de venda da ficha (pede confirmação). Usa o preço de hoje: se já o subiste, a sugestão ajusta-se ou desaparece.',
      '"Mais barato noutro": compara, para cada ingrediente que já compraste de duas marcas ou fornecedores, o preço ao kg (ou litro, ou unidade) de cada um e diz quanto poupas a comprar o mais barato em vez do que compras agora (o de preço mais recente). Só conta preços dos últimos 150 dias e diferenças a partir de 3 %. Os preços vêm das faturas que aplicas — quanto mais faturas, mais fiável. Não troca nada sozinho: serve para decidires a próxima compra.',
    ],
  ),
  HelpTopic.embalagens: (
    titulo: 'Embalagens',
    paragrafos: [
      'Caixas, sacos, saquetas, adesivos, fita… — tudo o que embala o produto.',
      'Preço da compra + quantas peças vêm nessa compra → custo por peça.',
      '"Uma peça embala quantas unidades?": um saco embala 1; uma caixa de 6 embala 6. O custo por unidade de produto divide-se por esse número.',
      'Tipo (Caixa, Saco, Saqueta…): escreve um novo a qualquer momento se o que precisas não estiver na lista — não é fixo.',
      'Característica (opcional) e Uso: "Individual" (1 cookie por embalagem) ou "Múltiplo" — escolhe a quantidade (2, 3, 4, 5, 6, 8, 10 ou 12) num toque. Podes também dizer para que Formatos de cookie serve cada embalagem.',
      'Na ficha técnica, adiciona a embalagem como uma linha (tipo "Embalagem") e o custo entra no total do produto — sem afetar o peso nem a informação nutricional.',
      '"+" cria; toque edita; toque e segure apaga. O botão de ordenar (seta) organiza as peças por Nome ou Custo por unidade.',
      'Separador "Kits": junta várias embalagens numa combinação com nome (ex.: "Take-away" = 1 saqueta + 1 caixa + 1 saco + 2 adesivos). Na ficha técnica escolhes o kit para precificar tudo de uma vez. O custo do kit atualiza-se sozinho quando muda o preço de qualquer embalagem que o compõe.',
    ],
  ),
  HelpTopic.consumiveis: (
    titulo: 'Limpeza e insumos',
    paragrafos: [
      'Produtos de limpeza, desinfeção e insumos que exigem documentação, e também Bebidas ou outra Revenda — o que compras para vender ao cliente, não para as receitas. A categoria decide se pede ficha de segurança (Limpeza/Desinfeção pedem por omissão; Bebida/Revenda não).',
      'Categoria: texto livre — escreve uma nova (ex.: "Sobremesas") sempre que precisares, não é uma lista fechada.',
      '"Preço de venda" (opcional): para Bebidas/Revenda vendidas ao cliente — dá para veres a margem. Fica em branco nos produtos que não se vendem (limpeza, insumos).',
      'Em cada produto anexas a ficha de dados de segurança (FDS) que o fornecedor te dá, a ficha técnica e certificados. Ficam organizados e abrem com um toque, prontos para uma fiscalização.',
      'O estado mostra "Falta FDS" se o produto exige a ficha e não tem nenhuma, e "FDS antiga" quando a última tem mais de 3 anos (pede ao fornecedor a versão mais recente, se existir).',
      'O filtro "A precisar de FDS" lista só o que falta tratar; os chips de categoria filtram por Limpeza/Bebida/Revenda/etc. O ícone de copiar junta o registo de todos os produtos (CSV) para colar numa folha de cálculo.',
      'O botão de ordenar (seta) organiza por Nome ou Estado FDS.',
      'Nas faturas, as linhas de limpeza/insumos/bebidas/revenda podem ser ligadas a estes produtos: o preço fica registado e, se já tiverem documentos, não é preciso pedi-los outra vez.',
    ],
  ),
  HelpTopic.configuracoes: (
    titulo: 'Configurações',
    paragrafos: [
      'As Configurações são uma lista de grupos, cada um com o estado à vista por baixo (ex.: "Backup com problema", "Resumo diário às 08:00", "Vendus sincronizado há 2 h"). Toca num grupo para abrir a sua página — o que está a vermelho pede atenção.',
      'Empresa e aparência: nome, moeda, regra de arredondamento, modo claro/escuro, cor da app, logótipo e tipo de letra. Aplica-se a toda a equipa.',
      'Segurança e backups, 2 passos: verificação em 2 passos (só o proprietário liga): quem entra como proprietário ou administrador passa a precisar também de um código de 6 dígitos enviado por email — escreve-se no ecrã a seguir ao login e entra sozinho ao completar os 6 dígitos. A equipa e o quiosque não são afetados. Precisa de o servidor enviar emails (SMTP).',
      'Segurança e backups, backups (só administradores): mostra o último backup automático do servidor (um por noite), quantos há guardados e se a cópia para fora do servidor (Google Drive/B2, cifrada) correu bem. Mostra também o espaço livre do servidor (avisa abaixo de 15 % ou 2 GB), o teste semanal que confirma que o último backup não está estragado (botão "Testar o último backup agora" para não esperar) e o teste de restauro mensal feito pelo servidor. Se algo falha ou está atrasado há mais de 30 h, aparece um aviso aqui e um cartão "Backup com problema" no Início. "Sem informação" na cópia externa quer dizer que o script ainda não correu (ver docs/BACKUPS.md).',
      'Custos e IVA: percentuais de custo (tudo sobre o preço sem IVA) — defines o CMV (matéria-prima) e os custos (salário, aluguer, serviços…); a margem de lucro é o que sobra — sobe se reduzires custos, desce se os aumentares, e o CMV não muda. O preço sugerido é custo ÷ CMV. O "IVA das vendas" é à parte: soma-se no fim sobre o preço sem IVA e estima o IVA a entregar na Contabilidade. Já não há "Impostos" nos percentuais (era o IVA).',
      'Equipa, Navegação e permissões, Avisos, Ligações (token do Vendus) e Saúde dos dados têm página própria, acessível aqui. Os formatos de cookie criam-se na própria ficha técnica e as categorias na própria receita.',
    ],
  ),
  HelpTopic.navegacao: (
    titulo: 'Navegação e permissões',
    paragrafos: [
      'Rodapé: escolha que páginas aparecem na barra de baixo (até 3, além do Início e do "Mais") e a ordem. Todas as outras abrem pelo "Mais". Proprietário e Administrador podem mudar.',
      'Permissões: só o Proprietário. Para cada nível (Administrador, Editor, Leitura) e cada página, escolha Oculto (a página desaparece e não abre), Só ver (vê mas não altera) ou Editar.',
      'O Proprietário tem sempre acesso a tudo. As permissões escondem e bloqueiam na app; os dados continuam protegidos pelo papel de cada pessoa.',
      'Cada pessoa pode ainda mudar a cor do ícone de cada página: no "Mais", mantém o dedo no ícone — isso é só para si.',
    ],
  ),
  HelpTopic.equipa: (
    titulo: 'Equipa',
    paragrafos: [
      'As pessoas que podem entrar na app desta empresa.',
      'Cada uma tem um papel: Proprietário e Administrador podem mudar tudo; Editor cria e edita; Leitura só vê.',
      'Use "+" para convidar alguém. Toque num membro para mudar o papel.',
    ],
  ),
};
